-- Migration: Add Nifty Smallcap 50 key companies to scalper_watchlist table

insert into scalper_watchlist (symbol, name, active) values
  ('AEGISCHEM.NS', 'Aegis Logistics Ltd', true),
  ('AFFLE.NS', 'Affle (India) Ltd', true),
  ('ARE&M.NS', 'Amara Raja Energy & Mobility Ltd', true),
  ('AMBER.NS', 'Amber Enterprises India Ltd', true),
  ('ANANDRATHI.NS', 'Anand Rathi Wealth Ltd', true),
  ('ANGELONE.NS', 'Angel One Ltd', true),
  ('ASTERDM.NS', 'Aster DM Healthcare Ltd', true),
  ('BANDHANBNK.NS', 'Bandhan Bank Ltd', true),
  ('CASTROLIND.NS', 'Castrol India Ltd', true),
  ('CDSL.NS', 'Central Depository Services (India) Ltd', true),
  ('CUB.NS', 'City Union Bank Ltd', true),
  ('COHANCE.NS', 'Cohance Lifesciences Ltd', true),
  ('CAMS.NS', 'Computer Age Management Services Ltd (CAMS)', true),
  ('CROMPTON.NS', 'Crompton Greaves Consumer Electricals Ltd', true),
  ('DELHIVERY.NS', 'Delhivery Ltd', true),
  ('LALPATHLAB.NS', 'Dr. Lal PathLabs Ltd', true),
  ('FIVESTAR.NS', 'Five-Star Business Finance Ltd', true),
  ('GLAND.NS', 'Gland Pharma Ltd', true),
  ('HSCL.NS', 'Himadri Speciality Chemical Ltd', true),
  ('HINDCOPPER.NS', 'Hindustan Copper Ltd', true),
  ('IIFL.NS', 'IIFL Finance Ltd', true),
  ('IGL.NS', 'Indraprastha Gas Ltd', true),
  ('INOXWIND.NS', 'Inox Wind Ltd', true),
  ('KARURVYSYA.NS', 'Karur Vysya Bank Ltd', true),
  ('KAYNES.NS', 'Kaynes Technology India Ltd', true),
  ('KEC.NS', 'KEC International Ltd', true),
  ('KFINTECH.NS', 'KFin Technologies Ltd', true),
  ('MANAPPURAM.NS', 'Manappuram Finance Ltd', true),
  ('NH.NS', 'Narayana Hrudayalaya Ltd', true),
  ('NATCOPHARM.NS', 'Natco Pharma Ltd', true),
  ('NAVINFLUOR.NS', 'Navin Fluorine International Ltd', true),
  ('NBCC.NS', 'NBCC (India) Ltd', true),
  ('NEULANDLAB.NS', 'Neuland Laboratories Ltd', true),
  ('PGEL.NS', 'PG Electroplast Ltd', true),
  ('PPLPHARMA.NS', 'Piramal Pharma Ltd', true),
  ('PNBHOUSING.NS', 'PNB Housing Finance Ltd', true),
  ('POONAWALLA.NS', 'Poonawalla Fincorp Ltd', true),
  ('RBLBANK.NS', 'RBL Bank Ltd', true),
  ('REDINGTON.NS', 'Redington Ltd', true),
  ('SAILIFE.NS', 'Sai Life Sciences Ltd', true),
  ('SONACOMS.NS', 'Sona BLW Precision Forgings Ltd', true),
  ('SYNGENE.NS', 'Syngene International Ltd', true),
  ('TATACHEM.NS', 'Tata Chemicals Ltd', true),
  ('TATATECH.NS', 'Tata Technologies Ltd', true),
  ('WELCORP.NS', 'Welspun Corp Ltd', true),
  ('WOCKPHARMA.NS', 'Wockhardt Ltd', true),
  ('ZENSARTECH.NS', 'Zensar Technologies Ltd', true)
on conflict (symbol) do update set name = excluded.name, active = true;
